on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  check-commits:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      build-tool: uv
      python-version: '3.13'

  build-container-image:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        flutter-version: ["3.19", "3.22", "3.24", "3.27"]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-kaniko.yml@v7
    with:
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'warp-ubuntu-2404-arm64-2x' || 'ubuntu-24.04' }}
      additional-build-args: |
        FLUTTER_VERSION=${{ matrix.flutter-version }}
      image-name: flutter
      push-image: false

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    with:
      build-tool: uv
      python-version: '3.13'

  push-container-images:
    if: needs.bump.outputs.bumped == 'true' && github.ref_name == github.event.repository.default_branch
    needs: bump
    strategy:
      matrix:
        flutter-version: ["3.19", "3.22", "3.24", "3.27"]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-kaniko.yml@v7
    with:
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'warp-ubuntu-2404-arm64-2x' || 'ubuntu-24.04' }}
      digest-artifact-name: digests-${{ matrix.flutter-version }}
      additional-build-args: |
        FLUTTER_VERSION=${{ matrix.flutter-version }}
      image-name: flutter
      push-image: true
      version: ${{ needs.bump.outputs.version }}-${{ matrix.flutter-version }}
      tag-suffix: -${{ matrix.platform }}

  merge-container-images:
    needs:
      - bump
      - push-container-images
    strategy:
      matrix:
        flutter-version: ["3.19", "3.22", "3.24", "3.27"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/merge-manifests.yml@v7
    with:
      image-name: flutter
      tag: ${{ needs.bump.outputs.version }}-${{ matrix.flutter-version }}
      variant-digests: digests-${{ matrix.flutter-version }}
