on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  required-meta:
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  check-commits:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      build-tool: uv
      python-version: '3.13'

  build-container-image:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        flutter-version: ["3.22", "3.24", "3.27", "3.29", "3.32"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-dual-image-kaniko.yml@v7
    with:
      additional-build-args: |
        FLUTTER_VERSION=${{ matrix.flutter-version }}
      image-name: flutter
      push-image: false

  post-build-container-image:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    needs: build-container-image
    steps:
      - run: echo "All images built"

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    with:
      build-tool: uv
      python-version: '3.13'

  push-container-images:
    if: needs.bump.outputs.bumped == 'true' && github.ref_name == github.event.repository.default_branch
    needs: bump
    strategy:
      matrix:
        flutter-version: ["3.22", "3.24", "3.27", "3.29", "3.32"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-dual-image-kaniko.yml@v7
    with:
      additional-build-args: |
        FLUTTER_VERSION=${{ matrix.flutter-version }}
      image-name: flutter
      push-image: true
      version: ${{ needs.bump.outputs.version }}-${{ matrix.flutter-version }}
