on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  check-commits:
    if: github.event_name == 'pull_request'
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v2
    with:
      python-version: '3.12'

  build-container-image:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        flutter-version: ["3.22"]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'ubicloud-standard-2-arm' || 'ubuntu-latest' }}
      additional-build-args: |
        FLUTTER_VERSION=${{ matrix.flutter-version }}
      image-name: flutter
      push-image: false

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v2
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    with:
      python-version: '3.12'

  push-container-images:
    if: needs.bump.outputs.bumped == 'true' && github.ref_name == github.event.repository.default_branch
    needs: bump
    strategy:
      matrix:
        flutter-version: ["3.22"]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-kaniko.yml@v3
    with:
      runner-name-build: ${{ (matrix.platform == 'arm64') && 'ubicloud-standard-2-arm' || 'ubuntu-latest' }}
      digest-artifact-name: digests-${{ matrix.flutter-version }}
      additional-build-args: |
        FLUTTER_VERSION=${{ matrix.flutter-version }}
      image-name: flutter
      push-image: true
      version: ${{ needs.bump.outputs.version }}-${{ matrix.flutter-version }}
      tag-suffix: -${{ matrix.platform }}

  merge-container-images:
    needs:
      - bump
      - push-container-images
    strategy:
      matrix:
        flutter-version: ["3.22"]
        platform: ["arm64", "amd64"]
    uses: BlindfoldedSurgery/actions-container/.github/workflows/merge-manifests.yml@v3
    with:
      image-name: flutter
      tag: ${{ needs.bump.outputs.version }}-${{ matrix.flutter-version }}
      variant-digests: digests-${{ matrix.flutter-version }}
